package avance2proyecto_alexanderalpizarm;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class PantallaProductos extends javax.swing.JFrame {
    private Cajero cajeroActual;
    private Orden ordenActual;
    
    public PantallaProductos() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public PantallaProductos(Cajero cajero, Orden orden) {
        initComponents();
        setLocationRelativeTo(null);

        this.cajeroActual = cajero;
        this.ordenActual = orden;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BVolverProductos = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnRegistrarProducto = new javax.swing.JButton();
        btnModificarProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnMostrarProductos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrarProductos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BVolverProductos.setText("Volver al Menú");
        BVolverProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVolverProductosActionPerformed(evt);
            }
        });

        btnEliminarProducto.setText("Eliminar Productos");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        btnRegistrarProducto.setText("Agregar Productos");
        btnRegistrarProducto.setActionCommand("Agregar Producto");
        btnRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProductoActionPerformed(evt);
            }
        });

        btnModificarProducto.setText("Modificar Productos");
        btnModificarProducto.setActionCommand("Modificar Producto");
        btnModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProductoActionPerformed(evt);
            }
        });

        jLabel1.setText("Gestion de Productos");

        btnMostrarProductos.setText("Mostrar Productos");
        btnMostrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarProductosActionPerformed(evt);
            }
        });

        txtMostrarProductos.setColumns(20);
        txtMostrarProductos.setRows(5);
        jScrollPane1.setViewportView(txtMostrarProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(BVolverProductos))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMostrarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(BVolverProductos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarProducto)
                    .addComponent(btnModificarProducto)
                    .addComponent(btnEliminarProducto))
                .addGap(12, 12, 12)
                .addComponent(btnMostrarProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProductoActionPerformed
        String datoId = JOptionPane.showInputDialog("Ingrese el ID del producto:");

        if (datoId == null || datoId.trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debe ingresar el ID del producto.");

            return;
        }

        String nombre = JOptionPane.showInputDialog("Ingrese el nombre del producto:");

        if (nombre == null || nombre.trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debe ingresar el nombre del producto.");

            return;
        }

        String datoPrecio = JOptionPane.showInputDialog("Ingrese el precio del producto:");

        if (datoPrecio == null || datoPrecio.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el precio del producto.");

            return;
        }

        String categoria = JOptionPane.showInputDialog("Ingrese la categoría del producto:");

        if (categoria == null || categoria.trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debe ingresar la categoría del producto.");

            return;
        }

        try {

            int id = Integer.parseInt(datoId);
            double precio = Double.parseDouble(datoPrecio);

            if (id <= 0){

                JOptionPane.showMessageDialog(null,"El ID debe ser mayor a cero.");

                return;
            }

            if (precio <= 0){
                JOptionPane.showMessageDialog(null, "El precio debe ser mayor a cero.");

                return;
            }

            ArchivosProductos archivo = new ArchivosProductos();
            ArrayList<Producto> productos = archivo.leerProductos();

            //Valida que el ID no esté repetido
            for (Producto producto : productos){

                if (producto.getId() == id){
                    JOptionPane.showMessageDialog(null,"Ya existe un producto con ese ID.");

                    return;
                }
            }

            Producto nuevoProducto = new Producto(id,nombre,precio,categoria);
            productos.add(nuevoProducto);
            ArchivosProductos.guardarProductos(productos);
            nuevoProducto.registrarProducto();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID y el precio deben ser números válidos.");
        }
    }//GEN-LAST:event_btnRegistrarProductoActionPerformed

    private void btnModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProductoActionPerformed
        ArchivosProductos archivo = new ArchivosProductos();

        ArrayList<Producto> productos = archivo.leerProductos();

        String datoId = JOptionPane.showInputDialog("Ingrese el ID del producto que desea modificar:");

        if (datoId == null || datoId.trim().isEmpty()){
            return;
        }

        try {

            int id = Integer.parseInt(datoId);

            boolean encontrado = false;

            for (Producto producto : productos){
                if (producto.getId() == id){

                    String nuevoNombre = JOptionPane.showInputDialog("Ingrese el nuevo nombre:",producto.getNombre());

                    if (nuevoNombre == null || nuevoNombre.trim().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Debe ingresar un nombre.");

                        return;
                    }

                    String datoPrecio = JOptionPane.showInputDialog("Ingrese el nuevo precio:",producto.getPrecio());

                    if (datoPrecio == null || datoPrecio.trim().isEmpty()) {
                        JOptionPane.showMessageDialog(null,"Debe ingresar un precio.");

                        return;
                    }

                    String nuevaCategoria = JOptionPane.showInputDialog("Ingrese la nueva categoría:",producto.getCategoria());

                    if (nuevaCategoria == null || nuevaCategoria.trim().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Debe ingresar una categoría.");

                        return;
                    }

                    double nuevoPrecio = Double.parseDouble(datoPrecio);

                    if (nuevoPrecio <= 0){
                        JOptionPane.showMessageDialog(null,"El precio debe ser mayor a cero.");

                        return;
                    }

                    producto.setNombre(nuevoNombre);
                    producto.setPrecio(nuevoPrecio);
                    producto.setCategoria(nuevaCategoria);

                    ArchivosProductos.guardarProductos(productos);
                    producto.modificarProducto();

                    encontrado = true;

                    break;
                }
            }

            if (!encontrado){
                JOptionPane.showMessageDialog(null, "No existe un producto con ese ID.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"El ID y el precio deben ser números válidos.");
        }
    }//GEN-LAST:event_btnModificarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        ArchivosProductos archivo = new ArchivosProductos();

        ArrayList<Producto> productos = archivo.leerProductos();

        String datoId = JOptionPane.showInputDialog("Ingrese el ID del producto que desea eliminar:");

        if (datoId == null || datoId.trim().isEmpty()){
            return;
        }

        try {

            int id = Integer.parseInt(datoId);

            boolean encontrado = false;

            for (Producto producto : productos){
                if (producto.getId() == id){
                    int opcion = JOptionPane.showConfirmDialog(null,"¿Está seguro de eliminar el producto?","Eliminar Producto",JOptionPane.YES_NO_OPTION);
                    if (opcion == JOptionPane.YES_OPTION){
                        productos.remove(producto);
                        ArchivosProductos.guardarProductos(productos);
                        producto.eliminarProducto();
                    }
                    encontrado = true;
                    break;
                }
            }

            if (!encontrado){
                JOptionPane.showMessageDialog(null,"No existe un producto con ese ID.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Debe ingresar un ID válido.");

        }
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void BVolverProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVolverProductosActionPerformed
        PantallaPrincipalCajero pantalla = new PantallaPrincipalCajero(cajeroActual, ordenActual);
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_BVolverProductosActionPerformed

    private void btnMostrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarProductosActionPerformed
        ArchivosProductos archivo = new ArchivosProductos();
        ArrayList<Producto> productos = archivo.leerProductos();

        txtMostrarProductos.setText("");
        txtMostrarProductos.append("ID\tNombre\t\tPrecio\tCategoría\n");
        txtMostrarProductos.append("------------------------------------------------------------\n");

        if (productos.isEmpty()) {
            txtMostrarProductos.append("No hay productos registrados.\n");

            return;
        }

        for (Producto producto : productos){
            txtMostrarProductos.append(producto.getId() + "\t"+ producto.getNombre() + "\t\t₡"+ producto.getPrecio() + "\t"
                    + producto.getCategoria() + "\n");
        }
    }//GEN-LAST:event_btnMostrarProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BVolverProductos;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnModificarProducto;
    private javax.swing.JButton btnMostrarProductos;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtMostrarProductos;
    // End of variables declaration//GEN-END:variables
}
