package avance2proyecto_alexanderalpizarm;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class PantallaFacturacion extends javax.swing.JFrame {
    private Cajero cajeroActual;
    private Orden ordenActual;
    private Factura facturaActual;
    private boolean ordenPagada;

    public PantallaFacturacion() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public PantallaFacturacion(Cajero cajero, Orden orden) {

        initComponents();
        setLocationRelativeTo(null);

        this.cajeroActual = cajero;
        this.ordenActual = orden;
        this.ordenPagada = false;

        mostrarFactura();
    }
    
    private void mostrarFactura() {

        txtDetalleFactura.setText("");

        if (ordenActual == null) {

            txtDetalleFactura.setText(
                    "No hay una orden para facturar.");

            return;
        }

        // El total de la orden ya incluye el IVA
        double total = ordenActual.calcularTotal();

        // Se obtiene el subtotal sin IVA
        double subtotal = total / 1.13;

        // Se obtiene cuánto corresponde al IVA
        double impuesto = total - subtotal;

        txtDetalleFactura.append(
                "FIDEBURGUESAS\n");

        txtDetalleFactura.append(
                "====================================\n");

        txtDetalleFactura.append(
                "Orden #: "
                + ordenActual.getId()
                + "\n");

        txtDetalleFactura.append(
                "Cliente: "
                + ordenActual.getCliente()
                + "\n");

        if (cajeroActual != null) {

            txtDetalleFactura.append(
                    "Cajero: "
                    + cajeroActual.getNombre()
                    + "\n");
        }

        txtDetalleFactura.append(
                "Fecha: "
                + ordenActual.getFecha()
                + "\n");

        txtDetalleFactura.append(
                "Estado: "
                + ordenActual.getEstado()
                + "\n");

        txtDetalleFactura.append(
                "====================================\n");

        txtDetalleFactura.append(
                "Detalle:\n\n");

        for (ItemOrden item : ordenActual.getItems()) {

            if (item.esProducto()) {

                txtDetalleFactura.append(
                        item.getCantidad()
                        + " x "
                        + item.getProducto().getNombre()
                        + " - ₡"
                        + String.format("%.2f", item.getSubtotal())
                        + "\n");

            } else if (item.esCombo()) {

                txtDetalleFactura.append(
                        item.getCantidad()
                        + " x Combo: "
                        + item.getCombo().getNombre()
                        + " - ₡"
                        + String.format("%.2f", item.getSubtotal())
                        + "\n");
            }
        }

        txtDetalleFactura.append(
                "\n------------------------------------\n");

        txtDetalleFactura.append(
                "Subtotal (sin IVA): ₡"
                + String.format("%.2f", subtotal)
                + "\n");

        txtDetalleFactura.append(
                "IVA (13% incluido): ₡"
                + String.format("%.2f", impuesto)
                + "\n");

        txtDetalleFactura.append(
                "TOTAL: ₡"
                + String.format("%.2f", total)
                + "\n");

        txtDetalleFactura.append(
                "====================================\n");
    }
    
    private void actualizarOrdenGuardada() {

        ArchivosOrdenes archivoOrdenes =
                new ArchivosOrdenes();

        ArrayList<Orden> ordenes =
                archivoOrdenes.leerOrdenes();

        boolean encontrada = false;

        for (int i = 0; i < ordenes.size(); i++) {

            if (ordenes.get(i).getId()
                    == ordenActual.getId()) {

                ordenes.set(i, ordenActual);

                encontrada = true;

                break;
            }
        }

        if (!encontrada) {

            ordenes.add(ordenActual);
        }

        ArchivosOrdenes.guardarOrdenes(ordenes);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMarcarPagada = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalleFactura = new javax.swing.JTextArea();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Factura");

        jLabel2.setText("FideBurguesas");

        btnMarcarPagada.setText("Marcar Orden como Pagada");
        btnMarcarPagada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarPagadaActionPerformed(evt);
            }
        });

        txtDetalleFactura.setColumns(20);
        txtDetalleFactura.setRows(5);
        jScrollPane1.setViewportView(txtDetalleFactura);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnMarcarPagada, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnVolver)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMarcarPagada)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarcarPagadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarPagadaActionPerformed
        if (ordenActual == null) {

            JOptionPane.showMessageDialog(null,
                    "No hay una orden para marcar como pagada.");

            return;
        }

        if (ordenPagada) {

            JOptionPane.showMessageDialog(null,
                    "La orden ya fue marcada como pagada.");

            return;
        }

        ArchivosFacturas archivoFacturas =
                new ArchivosFacturas();

        ArrayList<Factura> facturas =
                archivoFacturas.leerFacturas();

        int idFactura = 1;

        for (Factura factura : facturas) {

            if (factura.getId() >= idFactura) {

                idFactura = factura.getId() + 1;
            }
        }

        facturaActual = new Factura(idFactura, ordenActual);

        facturaActual.generarFactura();

        facturas.add(facturaActual);

        ArchivosFacturas.guardarFacturas(facturas);

        ordenActual.cambiarEstado("Pagada");

        actualizarOrdenGuardada();

        ordenPagada = true;

        btnMarcarPagada.setEnabled(false);

        mostrarFactura();

        JOptionPane.showMessageDialog(null,
                "Orden marcada como pagada.");
    }//GEN-LAST:event_btnMarcarPagadaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        PantallaPrincipalCajero pantalla;

        // Siempre conservar la orden al volver
        pantalla = new PantallaPrincipalCajero(cajeroActual, ordenActual);
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaFacturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarcarPagada;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDetalleFactura;
    // End of variables declaration//GEN-END:variables
}
