package avance2proyecto_alexanderalpizarm;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class PantallaPrincipalCajero extends javax.swing.JFrame {
    private Cajero cajeroActual;
    private Orden ordenActual;
    
    public PantallaPrincipalCajero() {
        initComponents();
        setLocationRelativeTo(null);
        
        BVolverAdministrador.setVisible(false);
        BLimpiarHistorico.setVisible(false);
    }
    
    public PantallaPrincipalCajero(Cajero cajero, Orden orden) {

        initComponents();
        setLocationRelativeTo(null);

        this.cajeroActual = cajero;
        this.ordenActual = orden;

        if (cajeroActual != null){
            lblNombreCajero.setText(cajeroActual.getNombre());
        }

        // Mostrar el botón solo al administrador
        if (cajeroActual != null && cajeroActual.getUsuario().equals("admin")) {
            BVolverAdministrador.setVisible(true);
            BLimpiarHistorico.setVisible(true);

        } 
        else {
            BVolverAdministrador.setVisible(false);
            BLimpiarHistorico.setVisible(false);
        }
        mostrarOrden();
    }
    
    private void mostrarOrden(){
        txtOrdenActual.setText("");
        if (ordenActual == null){
            txtOrdenActual.setText("No hay una orden creada.");
            return;
        }

        txtOrdenActual.append("Número de orden: " + ordenActual.getId()+ "\n");
        txtOrdenActual.append("Cliente: "+ ordenActual.getCliente()+ "\n");
        txtOrdenActual.append("Estado: "+ ordenActual.getEstado()+ "\n\n");

        for (ItemOrden item : ordenActual.getItems()){
            if (item.esProducto()){
                txtOrdenActual.append(item.getCantidad()+ " x "+ item.getProducto().getNombre()+ "  ₡"+ item.getSubtotal()+ "\n");

            } 
            else if (item.esCombo()){
                txtOrdenActual.append(item.getCantidad()+ " x Combo: "+ item.getCombo().getNombre()+ "  ₡"+ item.getSubtotal()+ "\n");
            }
        }

        txtOrdenActual.append("\n-----------------------------\n");
        txtOrdenActual.append("TOTAL: ₡"+ ordenActual.calcularTotal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BCerrarSesion = new javax.swing.JButton();
        BCombos = new javax.swing.JButton();
        BNuevaOrden = new javax.swing.JButton();
        BProductos = new javax.swing.JButton();
        BCancelarBorrar = new javax.swing.JButton();
        BEnviarCocina = new javax.swing.JButton();
        BFacturar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrdenActual = new javax.swing.JTextArea();
        lblNombreCajero = new javax.swing.JLabel();
        BHistoricoOrdenes = new javax.swing.JButton();
        BCocina = new javax.swing.JButton();
        BVolverAdministrador = new javax.swing.JButton();
        BLimpiarHistorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FideBurguesas");

        jLabel2.setText("Cajero:");

        BCerrarSesion.setText("Cerrar Sesión");
        BCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCerrarSesionActionPerformed(evt);
            }
        });

        BCombos.setText("Combos");
        BCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCombosActionPerformed(evt);
            }
        });

        BNuevaOrden.setText("Nueva Orden");
        BNuevaOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevaOrdenActionPerformed(evt);
            }
        });

        BProductos.setText("Productos");
        BProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BProductosActionPerformed(evt);
            }
        });

        BCancelarBorrar.setText("Cancelar Orden");
        BCancelarBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarBorrarActionPerformed(evt);
            }
        });

        BEnviarCocina.setText("Enviar a Cocina");
        BEnviarCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEnviarCocinaActionPerformed(evt);
            }
        });

        BFacturar.setText("Facturar");
        BFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFacturarActionPerformed(evt);
            }
        });

        txtOrdenActual.setColumns(20);
        txtOrdenActual.setRows(5);
        jScrollPane1.setViewportView(txtOrdenActual);

        lblNombreCajero.setText("    ");

        BHistoricoOrdenes.setText("Ver Historico de Ordenes");
        BHistoricoOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHistoricoOrdenesActionPerformed(evt);
            }
        });

        BCocina.setText("Cocina");
        BCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCocinaActionPerformed(evt);
            }
        });

        BVolverAdministrador.setText("Gestionar Cajeros");
        BVolverAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVolverAdministradorActionPerformed(evt);
            }
        });

        BLimpiarHistorico.setText("Limpiar Historico");
        BLimpiarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimpiarHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNombreCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(BVolverAdministrador)
                                    .addGap(28, 28, 28)
                                    .addComponent(BCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BLimpiarHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BHistoricoOrdenes, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(BFacturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(287, 287, 287)
                                    .addComponent(BCancelarBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(417, 417, 417)))
                            .addGap(56, 56, 56)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BNuevaOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BEnviarCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(473, 473, 473))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lblNombreCajero)
                    .addComponent(BVolverAdministrador)
                    .addComponent(BCerrarSesion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BNuevaOrden)
                    .addComponent(BProductos)
                    .addComponent(BCombos)
                    .addComponent(BHistoricoOrdenes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BLimpiarHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BCancelarBorrar)
                    .addComponent(BFacturar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BEnviarCocina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BCocina)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCancelarBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarBorrarActionPerformed
        if (ordenActual == null) {
            JOptionPane.showMessageDialog(null,"No hay una orden para cancelar.");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(null,"¿Desea cancelar la orden actual?","Cancelar Orden",JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION){
            ordenActual = null;
            txtOrdenActual.setText("No hay una orden creada.");

            JOptionPane.showMessageDialog(null,"Orden cancelada correctamente.");
        }
    }//GEN-LAST:event_BCancelarBorrarActionPerformed

    private void BEnviarCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEnviarCocinaActionPerformed
        if (ordenActual == null){
            JOptionPane.showMessageDialog(null,"No hay una orden para enviar a cocina.");
            return;
        }

        // Verificar que la orden esté pagada
        if (!ordenActual.getEstado().equalsIgnoreCase("Pagada")){
            JOptionPane.showMessageDialog(null,"Primero debe marcar la orden como pagada.");
            return;
        }

        ArchivosOrdenes archivo = new ArchivosOrdenes();
        ArrayList<Orden> ordenes = archivo.leerOrdenes();
        boolean ordenExistente = false;

        for (Orden orden : ordenes){
            if (orden.getId() == ordenActual.getId()){
                ordenExistente = true;
                // Actualiza la orden existente
                orden.setEstadoCocina("Pendiente");
                break;
            }
        }

        if (!ordenExistente){
            ordenActual.setEstadoCocina("Pendiente");
            ordenes.add(ordenActual);
        }

        ArchivosOrdenes.guardarOrdenes(ordenes);

        JOptionPane.showMessageDialog(null,"Orden enviada a cocina correctamente.");
        // Limpia la orden actual
        ordenActual = null;
        txtOrdenActual.setText("No hay una orden creada.");
    }//GEN-LAST:event_BEnviarCocinaActionPerformed

    private void BFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFacturarActionPerformed
        if (ordenActual == null){
            JOptionPane.showMessageDialog(null,"No hay una orden para facturar.");
            return;
        }

        PantallaFacturacion pantalla = new PantallaFacturacion(cajeroActual, ordenActual);
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_BFacturarActionPerformed

    private void BNuevaOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevaOrdenActionPerformed
        PantallaOrdenNueva pantalla = new PantallaOrdenNueva(cajeroActual);
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_BNuevaOrdenActionPerformed

    private void BProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BProductosActionPerformed
        PantallaProductos pantalla = new PantallaProductos(cajeroActual,ordenActual);
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_BProductosActionPerformed

    private void BCombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCombosActionPerformed
        PantallaCombos pantalla = new PantallaCombos(cajeroActual, ordenActual);
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_BCombosActionPerformed

    private void BCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCerrarSesionActionPerformed
        dispose();
        new PantallaInicioSesion().setVisible(true);
    }//GEN-LAST:event_BCerrarSesionActionPerformed

    private void BHistoricoOrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHistoricoOrdenesActionPerformed
        ArchivosOrdenes archivo = new ArchivosOrdenes();

        ArrayList<Orden> ordenes = archivo.leerOrdenes();

        String historico = "HISTÓRICO DE ÓRDENES\n";
        historico += "====================================\n\n";

        boolean hayOrdenesPagadas = false;

        for (Orden orden : ordenes){
            //Muestra las órdenes pagadas
            if (orden.getEstado().equalsIgnoreCase("Pagada")){
                hayOrdenesPagadas = true;
                
                historico += "Orden #: "+ orden.getId()+ "\n";
                historico += "Cliente: "+ orden.getCliente() + "\n";
                historico += "Estado de pago: "+ orden.getEstado()+ "\n";
                historico += "Estado de cocina: "+ orden.getEstadoCocina()+ "\n";
                historico += "Detalle:\n";

                for (ItemOrden item : orden.getItems()){
                    if (item.esProducto()){
                        historico += item.getCantidad()+ " x "+ item.getProducto().getNombre()+ " - ₡"+ String.format("%.2f",item.getSubtotal())+ "\n";

                    } 
                    else if (item.esCombo()){
                        historico += item.getCantidad()+ " x Combo: "+ item.getCombo().getNombre()+ " - ₡"+ String.format("%.2f",item.getSubtotal())+ "\n";
                    }
                }

                double total = orden.calcularTotal();
                double subtotal = total / 1.13;
                double iva = total - subtotal;

                historico += "\nSubtotal sin IVA: ₡"+ String.format("%.2f", subtotal)+ "\n";
                historico += "IVA incluido: ₡"+ String.format("%.2f", iva)+ "\n";
                historico += "Total de la orden: ₡" + String.format("%.2f", total)+ "\n";
                historico += "------------------------------------\n\n";
            }
        }

        if (!hayOrdenesPagadas){
            JOptionPane.showMessageDialog(null,"No hay órdenes pagadas en el histórico.");

            return;
        }

        JOptionPane.showMessageDialog(null,historico,"Histórico de Órdenes",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BHistoricoOrdenesActionPerformed

    private void BCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCocinaActionPerformed
        PantallaCocina pantalla = new PantallaCocina(cajeroActual, ordenActual);
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_BCocinaActionPerformed

    private void BVolverAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVolverAdministradorActionPerformed
        PantallaAdministrador pantalla = new PantallaAdministrador();
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_BVolverAdministradorActionPerformed

    private void BLimpiarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimpiarHistoricoActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar todo el historial de órdenes y facturas?", "Confirmar", JOptionPane.YES_NO_OPTION);

        if (opcion != JOptionPane.YES_OPTION){
            return;
        }

        ArrayList<Orden> ordenes = new ArrayList<>();
        ArchivosOrdenes.guardarOrdenes(ordenes);

        ArrayList<Factura> facturas = new ArrayList<>();
        ArchivosFacturas.guardarFacturas(facturas);

        JOptionPane.showMessageDialog(null,"Historial eliminado correctamente.");
    }//GEN-LAST:event_BLimpiarHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipalCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipalCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipalCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipalCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipalCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelarBorrar;
    private javax.swing.JButton BCerrarSesion;
    private javax.swing.JButton BCocina;
    private javax.swing.JButton BCombos;
    private javax.swing.JButton BEnviarCocina;
    private javax.swing.JButton BFacturar;
    private javax.swing.JButton BHistoricoOrdenes;
    private javax.swing.JButton BLimpiarHistorico;
    private javax.swing.JButton BNuevaOrden;
    private javax.swing.JButton BProductos;
    private javax.swing.JButton BVolverAdministrador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreCajero;
    private javax.swing.JTextArea txtOrdenActual;
    // End of variables declaration//GEN-END:variables
}
