package avance2proyecto_alexanderalpizarm;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class PantallaOrdenNueva extends javax.swing.JFrame {
    private Cajero cajeroActual;
    private Orden ordenActual;

    public PantallaOrdenNueva() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public PantallaOrdenNueva(Cajero cajero) {
        initComponents();
        setLocationRelativeTo(null);
        this.cajeroActual = cajero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalleOrden = new javax.swing.JTextArea();
        txtNombreCliente = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnVerMenu = new javax.swing.JButton();
        btnGuardarVolver = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del cliente: ");

        jLabel2.setText("Codigo de producto");

        jLabel3.setText("Cantidad");

        txtDetalleOrden.setColumns(20);
        txtDetalleOrden.setRows(5);
        jScrollPane1.setViewportView(txtDetalleOrden);

        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnVerMenu.setText("Ver Menu");
        btnVerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMenuActionPerformed(evt);
            }
        });

        btnGuardarVolver.setText("Guardar Volver");
        btnGuardarVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarVolverActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnVerMenu)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarVolver)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerMenu)
                    .addComponent(btnGuardarVolver)
                    .addComponent(btnCancelar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombreCliente = txtNombreCliente.getText();
        String datoCodigo = txtCodigo.getText();
        String datoCantidad = txtCantidad.getText();

        if (nombreCliente.trim().isEmpty() || datoCodigo.trim().isEmpty() || datoCantidad.trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debe completar todos los campos.");
            return;
        }

        try {

            int codigo = Integer.parseInt(datoCodigo);
            int cantidad = Integer.parseInt(datoCantidad);

            if (cantidad <= 0){
                JOptionPane.showMessageDialog(null,"La cantidad debe ser mayor a cero.");
                return;
            }

            // Crear la orden solamente la primera vez
            if (ordenActual == null){
                ArchivosOrdenes archivoOrdenes = new ArchivosOrdenes();
                ArrayList<Orden> ordenes = archivoOrdenes.leerOrdenes();

                int idOrden = 1;
                for (Orden orden : ordenes){

                    if (orden.getId() >= idOrden){
                        idOrden = orden.getId() + 1;
                    }
                }

                ordenActual = new Orden(idOrden,nombreCliente);
                txtNombreCliente.setEditable(false);
            }

            // Buscar primero en productos
            ArchivosProductos archivoProductos = new ArchivosProductos();
            ArrayList<Producto> productos = archivoProductos.leerProductos();
            Producto productoEncontrado = null;

            for (Producto producto : productos){
                if (producto.getId() == codigo){
                    productoEncontrado = producto;
                    break;
                }
            }

            if (productoEncontrado != null){
                ItemOrden item = new ItemOrden(productoEncontrado,cantidad);
                ordenActual.agregarItem(item);
                mostrarOrden();

                txtCodigo.setText("");
                txtCantidad.setText("");

                return;
            }

            // Si no se encuentra como producto, buscar como combo
            ArchivosCombos archivoCombos = new ArchivosCombos();
            ArrayList<Combo> combos = archivoCombos.leerCombos();
            Combo comboEncontrado = null;

            for (Combo combo : combos){

                if (combo.getId() == codigo){
                    comboEncontrado = combo;
                    break;
                }
            }

            if (comboEncontrado != null){
                ItemOrden item = new ItemOrden(comboEncontrado,cantidad);
                ordenActual.agregarItem(item);
                JOptionPane.showMessageDialog(null,"Combo agregado a la orden.");

                mostrarOrden();

                txtCodigo.setText("");
                txtCantidad.setText("");

                return;
            }

            JOptionPane.showMessageDialog(null,"No existe un producto o combo con ese código.");

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,"El código y la cantidad deben ser números.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarVolverActionPerformed
        if (ordenActual == null || ordenActual.getItems().isEmpty()){

            JOptionPane.showMessageDialog(null,"Debe agregar al menos un producto a la orden.");

            return;
        }

        PantallaPrincipalCajero pantalla = new PantallaPrincipalCajero(cajeroActual, ordenActual);
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGuardarVolverActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        PantallaPrincipalCajero pantalla = new PantallaPrincipalCajero(cajeroActual,null);
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMenuActionPerformed
        ArchivosProductos archivoProductos = new ArchivosProductos();
        ArrayList<Producto> productos = archivoProductos.leerProductos();

        ArchivosCombos archivoCombos = new ArchivosCombos();
        ArrayList<Combo> combos = archivoCombos.leerCombos();

        String menu = "MENÚ DE FIDEBURGUESAS\n\n";

        menu += "PRODUCTOS\n";
        menu += "--------------------------------------\n";

        if (productos.isEmpty()){
            menu += "No hay productos registrados.\n";
        } 
        else {
            for (Producto producto : productos){
                menu += "Código: " + producto.getId()+ " - " + producto.getNombre()+ " - ₡" + producto.getPrecio()+ "\n";
            }
        }

        menu += "\nCOMBOS\n";
        menu += "--------------------------------------\n";

        if (combos.isEmpty()){
            menu += "No hay combos registrados.\n";

        } 
        else {
            for (Combo combo : combos){

                menu += "Código: " + combo.getId()+ " - " + combo.getNombre()+ " - ₡" + combo.calcularPrecioTotal()+ "\n";
            }
        }

        JOptionPane.showMessageDialog(null,menu,"Menú",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVerMenuActionPerformed

    private void mostrarOrden() {
        txtDetalleOrden.setText("");

        if (ordenActual == null){
            txtDetalleOrden.setText("No hay una orden creada.");

            return;
        }

        txtDetalleOrden.append("Orden #: " + ordenActual.getId() + "\n");
        txtDetalleOrden.append("Cliente: " + ordenActual.getCliente() + "\n");
        txtDetalleOrden.append("Estado: " + ordenActual.getEstado() + "\n");
        txtDetalleOrden.append("------------------------------------------\n");

        for (ItemOrden item : ordenActual.getItems()){
            if (item.esProducto()){
                txtDetalleOrden.append(item.getCantidad()+ " x "+ item.getProducto().getNombre()+ " - ₡"+ item.getSubtotal()+ "\n");

            } 
            else if (item.esCombo()){

                txtDetalleOrden.append(item.getCantidad()+ " x Combo: "+ item.getCombo().getNombre()+ " - ₡"+ item.getSubtotal()+ "\n");
            }
        }

        txtDetalleOrden.append("------------------------------------------\n");
        txtDetalleOrden.append("Total: ₡"+ ordenActual.calcularTotal());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaOrdenNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaOrdenNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaOrdenNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaOrdenNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaOrdenNueva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardarVolver;
    private javax.swing.JButton btnVerMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDetalleOrden;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
