package avance2proyecto_alexanderalpizarm;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class PantallaCocina extends javax.swing.JFrame {
    private Cajero cajeroActual;
    private Orden ordenActual;
    
    public PantallaCocina() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public PantallaCocina(Cajero cajero, Orden orden) {
        initComponents();
        setLocationRelativeTo(null);
        this.cajeroActual = cajero;
        this.ordenActual = orden;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMarcarLista = new javax.swing.JButton();
        btnOrdenesPendientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrdenesPendientes = new javax.swing.JTextArea();
        btnVolverCajero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ORDENES PENDIENTES");

        btnMarcarLista.setText("Marcar como Listo");
        btnMarcarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarListaActionPerformed(evt);
            }
        });

        btnOrdenesPendientes.setText("Ver Ordenes Pendientes");
        btnOrdenesPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenesPendientesActionPerformed(evt);
            }
        });

        txtOrdenesPendientes.setColumns(20);
        txtOrdenesPendientes.setRows(5);
        jScrollPane1.setViewportView(txtOrdenesPendientes);

        btnVolverCajero.setText("Volver a Cajero");
        btnVolverCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverCajeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOrdenesPendientes)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMarcarLista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVolverCajero))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(btnOrdenesPendientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarcarLista)
                    .addComponent(btnVolverCajero))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarcarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarListaActionPerformed
        String datoId = JOptionPane.showInputDialog("Ingrese el ID de la orden que desea marcar como lista:");

        if (datoId == null || datoId.trim().isEmpty()){
            return;
        }

        try {

            int id = Integer.parseInt(datoId);
            ArchivosOrdenes archivo = new ArchivosOrdenes();
            ArrayList<Orden> ordenes = archivo.leerOrdenes();
            boolean encontrada = false;

            for (Orden orden : ordenes){
                if (orden.getId() == id){
                    encontrada = true;
                    if (orden.getEstadoCocina() != null && orden.getEstadoCocina().equalsIgnoreCase("Lista")){
                        JOptionPane.showMessageDialog(null,"La orden ya está marcada como lista.");
                        return;
                    }

                    orden.cambiarEstadoCocina("Lista");
                    ArchivosOrdenes.guardarOrdenes(ordenes);
                    JOptionPane.showMessageDialog(null,"Orden marcada como lista.");

                    btnOrdenesPendientesActionPerformed(evt);
                    return;
                }
            }

            if (!encontrada){
                JOptionPane.showMessageDialog(null,"No existe una orden con ese ID.");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,"Debe ingresar un ID válido.");
        }
    }//GEN-LAST:event_btnMarcarListaActionPerformed

    private void btnOrdenesPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenesPendientesActionPerformed
        ArchivosOrdenes archivo = new ArchivosOrdenes();
        ArrayList<Orden> ordenes = archivo.leerOrdenes();
        txtOrdenesPendientes.setText("");
        boolean hayPendientes = false;

        for (Orden orden : ordenes){
            String estadoPago = orden.getEstado();
            String estadoCocina = orden.getEstadoCocina();

            if (estadoPago != null && estadoCocina != null && estadoPago.equalsIgnoreCase("Pagada") && estadoCocina.equalsIgnoreCase("Pendiente")){
                hayPendientes = true;

                txtOrdenesPendientes.append("Orden #: " + orden.getId() + "\n");
                txtOrdenesPendientes.append("Cliente: " + orden.getCliente() + "\n");
                txtOrdenesPendientes.append("Estado de pago: " + estadoPago + "\n");
                txtOrdenesPendientes.append("Estado de cocina: " + estadoCocina + "\n");
                txtOrdenesPendientes.append("Detalle:\n");

                for (ItemOrden item : orden.getItems()){
                    if (item.esProducto()){
                        txtOrdenesPendientes.append(item.getCantidad()+ " x "+ item.getProducto().getNombre()+ "\n");

                    }
                    else if (item.esCombo()){
                        txtOrdenesPendientes.append(item.getCantidad()+ " x Combo: "+ item.getCombo().getNombre()+ "\n");
                        txtOrdenesPendientes.append("Productos del combo:\n");

                        for (Producto producto: item.getCombo().getProductos()){
                            txtOrdenesPendientes.append("   - "+ producto.getNombre()+ "\n");
                        }
                    }
                }
                txtOrdenesPendientes.append("----------------------------------------\n");
            }
        }

        if (!hayPendientes){

            txtOrdenesPendientes.setText("No hay órdenes pagadas y pendientes de preparar.");
        }
    }//GEN-LAST:event_btnOrdenesPendientesActionPerformed

    private void btnVolverCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverCajeroActionPerformed
        PantallaPrincipalCajero pantalla = new PantallaPrincipalCajero(cajeroActual, ordenActual);
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverCajeroActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCocina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarcarLista;
    private javax.swing.JButton btnOrdenesPendientes;
    private javax.swing.JButton btnVolverCajero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtOrdenesPendientes;
    // End of variables declaration//GEN-END:variables
}
