package avance2proyecto_alexanderalpizarm;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author alexa
 */
public class PantallaCombos extends javax.swing.JFrame {
    private Cajero cajeroActual;
    private Orden ordenActual;
    
    public PantallaCombos() {

        initComponents();
        setLocationRelativeTo(null);
    }

    public PantallaCombos(Cajero cajero, Orden orden) {

        initComponents();
        setLocationRelativeTo(null);

        this.cajeroActual = cajero;
        this.ordenActual = orden;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnMostrarCombos = new javax.swing.JButton();
        btnEliminarCombo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrarCombos = new javax.swing.JTextArea();
        btnRegistrarCombo = new javax.swing.JButton();
        btnModificarCombo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gestion de Combos");

        btnVolver.setText("Volver al Menú");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnMostrarCombos.setText("Mostrar Combos");
        btnMostrarCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCombosActionPerformed(evt);
            }
        });

        btnEliminarCombo.setText("Eliminar Combos");
        btnEliminarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarComboActionPerformed(evt);
            }
        });

        txtMostrarCombos.setColumns(20);
        txtMostrarCombos.setRows(5);
        jScrollPane1.setViewportView(txtMostrarCombos);

        btnRegistrarCombo.setText("Agregar Combos");
        btnRegistrarCombo.setActionCommand("Agregar Producto");
        btnRegistrarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarComboActionPerformed(evt);
            }
        });

        btnModificarCombo.setText("Modificar Combos");
        btnModificarCombo.setActionCommand("Modificar Producto");
        btnModificarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRegistrarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnMostrarCombos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnModificarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarCombo)
                    .addComponent(btnModificarCombo)
                    .addComponent(btnEliminarCombo))
                .addGap(12, 12, 12)
                .addComponent(btnMostrarCombos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        PantallaPrincipalCajero pantalla = new PantallaPrincipalCajero(cajeroActual, ordenActual);
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnMostrarCombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCombosActionPerformed
        ArchivosCombos archivo = new ArchivosCombos();
        ArrayList<Combo> combos = archivo.leerCombos();
        txtMostrarCombos.setText("");

        if (combos.isEmpty()){
            txtMostrarCombos.setText("No hay combos registrados.");
            return;
        }

        for (Combo combo : combos){
            txtMostrarCombos.append("ID: " + combo.getId() + "\n");
            txtMostrarCombos.append("Nombre del Combo: " + combo.getNombre() + "\n");
            txtMostrarCombos.append("Productos:\n");

            for (Producto producto : combo.getProductos()) {
                txtMostrarCombos.append("   • " + producto.getNombre()+ " - ₡" + producto.getPrecio()+ "\n");
            }

            txtMostrarCombos.append("Descuento: "+ (combo.getDescuento() * 100)+ "%\n");
            txtMostrarCombos.append("Precio del Combo: ₡"+ combo.calcularPrecioTotal()+ "\n");
            txtMostrarCombos.append("-------------------------------------------------\n");
        }
    }//GEN-LAST:event_btnMostrarCombosActionPerformed

    private void btnEliminarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarComboActionPerformed
        ArchivosCombos archivo = new ArchivosCombos();
        ArrayList<Combo> combos = archivo.leerCombos();
        String datoId = JOptionPane.showInputDialog("Ingrese el ID del combo que desea eliminar:");

        if (datoId == null || datoId.trim().isEmpty()){
            return;
        }

        try {

            int id = Integer.parseInt(datoId);
            boolean encontrado = false;
            for (int i = 0; i < combos.size(); i++){
                Combo combo = combos.get(i);
                
                if (combo.getId() == id){
                    int opcion = JOptionPane.showConfirmDialog( null,"¿Está seguro de eliminar el combo "+ combo.getNombre() + "?",
                            "Eliminar Combo",JOptionPane.YES_NO_OPTION);

                    if (opcion == JOptionPane.YES_OPTION){
                        combos.remove(i);
                        ArchivosCombos.guardarCombos(combos);
                        JOptionPane.showMessageDialog(null,"Combo eliminado correctamente.");
                    }
                    encontrado = true;
                    break;
                }
            }

            if (!encontrado){
                JOptionPane.showMessageDialog(null,"No existe un combo con ese ID.");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,"Debe ingresar un ID válido.");
        }
    }//GEN-LAST:event_btnEliminarComboActionPerformed

    private void btnRegistrarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarComboActionPerformed
        ArchivosProductos archivoProductos = new ArchivosProductos();
        ArrayList<Producto> productos = archivoProductos.leerProductos();
        if (productos.isEmpty()){
            JOptionPane.showMessageDialog(null, "Primero debe registrar productos.");
            return;
        }

        String datoIdCombo = JOptionPane.showInputDialog("Ingrese el ID del combo:");

        if (datoIdCombo == null || datoIdCombo.trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debe ingresar el ID del combo.");
            return;
        }

        String nombre = JOptionPane.showInputDialog("Ingrese el nombre del combo:");

        if (nombre == null || nombre.trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debe ingresar el nombre del combo.");
            return;
        }

        String datoDescuento = JOptionPane.showInputDialog("Ingrese el porcentaje de descuento:"+ "\nEjemplo: escriba 10 para un 10%.");

        if (datoDescuento == null || datoDescuento.trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debe ingresar el descuento.");
            return;
        }

        try {

            int idCombo = Integer.parseInt(datoIdCombo);
            double porcentaje = Double.parseDouble(datoDescuento);

            if (idCombo <= 0){

                JOptionPane.showMessageDialog(null,"El ID debe ser mayor a cero.");
                return;
            }

            if (porcentaje < 0 || porcentaje > 100){
                JOptionPane.showMessageDialog(null,"El descuento debe estar entre 0 y 100.");
                return;
            }

            ArchivosCombos archivoCombos = new ArchivosCombos();
            ArrayList<Combo> combos = archivoCombos.leerCombos();

            //Valida que el ID del combo no esté repetido
            for (Combo combo : combos) {
                if (combo.getId() == idCombo){
                    JOptionPane.showMessageDialog(null,"Ya existe un combo con ese ID.");
                    return;
                }
            }

            //evita que el combo tenga el mismo ID de un producto
            for (Producto producto : productos){
                if (producto.getId() == idCombo){
                    JOptionPane.showMessageDialog(null,"Ese ID ya está siendo utilizado por un producto.");
                    return;
                }
            }

            double descuento = porcentaje / 100;

            Combo nuevoCombo = new Combo(idCombo,nombre,descuento);

            boolean continuar = true;
            while (continuar){
                String lista = "PRODUCTOS DISPONIBLES\n\n";
                for (Producto producto : productos){

                    lista += "ID: "+ producto.getId()+ " - "+ producto.getNombre()+ " - ₡"+ producto.getPrecio()+ "\n";
                }

                String datoIdProducto = JOptionPane.showInputDialog(lista+ "\nIngrese el ID del producto "+ "que desea agregar."
                                + "\nPresione *Cancelar* "+ "cuando termine.");

                if (datoIdProducto == null){
                    continuar = false;

                } 
                else if (datoIdProducto.trim().isEmpty()){
                    JOptionPane.showMessageDialog(null,"Debe ingresar un ID.");

                } 
                else {
                    int idProducto = Integer.parseInt(datoIdProducto);
                    Producto productoEncontrado = null;
                    for (Producto producto : productos){
                        if (producto.getId() == idProducto) {
                            productoEncontrado = producto;
                            break;
                        }
                    }

                    if (productoEncontrado == null) {

                        JOptionPane.showMessageDialog(null, "No existe un producto " + "con ese ID.");
                    } 
                    else {

                        boolean repetido = false;

                        for (Producto productoCombo : nuevoCombo.getProductos()){
                            if (productoCombo.getId() == productoEncontrado.getId()) {
                                repetido = true;
                                break;
                            }
                        }

                        if (repetido){

                            JOptionPane.showMessageDialog(null,"Ese producto ya está incluido en el combo.");

                        } 
                        else {
                            nuevoCombo.agregarProducto(productoEncontrado);
                        }
                    }
                }
            }

            if (nuevoCombo.getProductos().isEmpty()){
                JOptionPane.showMessageDialog(null,"El combo debe tener al menos un producto.");
                return;
            }

            combos.add(nuevoCombo);
            ArchivosCombos.guardarCombos(combos);
            JOptionPane.showMessageDialog(null,"Combo registrado correctamente."+ "\nPrecio del combo: ₡"+ nuevoCombo.calcularPrecioTotal());

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,"Los ID y el descuento deben ser números válidos.");
        }
    }//GEN-LAST:event_btnRegistrarComboActionPerformed

    private void btnModificarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarComboActionPerformed
        ArchivosCombos archivoCombos = new ArchivosCombos();
        ArrayList<Combo> combos = archivoCombos.leerCombos();

        ArchivosProductos archivoProductos = new ArchivosProductos();
        ArrayList<Producto> productos = archivoProductos.leerProductos();

        String datoId = JOptionPane.showInputDialog("Ingrese el ID del combo que desea modificar:");

        if (datoId == null || datoId.trim().isEmpty()){
            return;
        }

        try {

            int id = Integer.parseInt(datoId);
            boolean encontrado = false;
            for (Combo combo : combos){
                if (combo.getId() == id){

                    encontrado = true;

                    String nuevoNombre = JOptionPane.showInputDialog("Ingrese el nuevo nombre:",combo.getNombre());
                    if (nuevoNombre == null || nuevoNombre.trim().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Debe ingresar un nombre.");
                        return;
                    }

                    String datoDescuento = JOptionPane.showInputDialog("Ingrese el nuevo porcentaje de descuento:",combo.getDescuento() * 100);

                    if (datoDescuento == null || datoDescuento.trim().isEmpty()){
                        JOptionPane.showMessageDialog(null,"Debe ingresar un descuento.");
                        return;
                    }

                    double porcentaje = Double.parseDouble(datoDescuento);

                    if (porcentaje < 0 || porcentaje > 100){
                        JOptionPane.showMessageDialog(null,"El descuento debe estar entre 0 y 100.");
                        return;
                    }

                    combo.setNombre(nuevoNombre);
                    combo.setDescuento(porcentaje / 100);

                    int opcion = JOptionPane.showConfirmDialog(null,"¿Desea cambiar los productos del combo?",
                            "Modificar Combo",JOptionPane.YES_NO_OPTION);

                    if (opcion == JOptionPane.YES_OPTION){
                        combo.getProductos().clear();
                        boolean continuar = true;
                        while (continuar) {
                            String lista = "PRODUCTOS DISPONIBLES\n\n";
                            for (Producto producto : productos){

                                lista += "ID: " + producto.getId()+ " - " + producto.getNombre()+ " - ₡" + producto.getPrecio()+ "\n";
                            }

                            String datoProducto = JOptionPane.showInputDialog(lista+ "\nIngrese el ID del producto."+ "\nPresione Cancelar cuando termine.");

                            if (datoProducto == null){
                                continuar = false;

                            } 
                            else if (datoProducto.trim().isEmpty()){
                                JOptionPane.showMessageDialog(null,"Debe ingresar un ID.");

                            } 
                            else {

                                int idProducto = Integer.parseInt(datoProducto);

                                Producto productoEncontrado = null;
                                for (Producto producto : productos){
                                    if (producto.getId() == idProducto){
                                        productoEncontrado = producto;
                                        break;
                                    }
                                }

                                if (productoEncontrado == null){
                                    JOptionPane.showMessageDialog(null,"No existe un producto con ese ID.");

                                } 
                                else {
                                    boolean repetido = false;
                                    for (Producto productoCombo: combo.getProductos()){
                                        if (productoCombo.getId() == productoEncontrado.getId()){
                                            repetido = true;
                                            break;
                                        }
                                    }

                                    if (repetido){
                                        JOptionPane.showMessageDialog(null,"Ese producto ya está en el combo.");

                                    } 
                                    else {
                                        combo.agregarProducto(productoEncontrado);
                                    }
                                }
                            }
                        }

                        if (combo.getProductos().isEmpty()){
                            JOptionPane.showMessageDialog(null, "El combo debe tener al menos un producto.");
                            return;
                        }
                    }
                    ArchivosCombos.guardarCombos(combos);
                    JOptionPane.showMessageDialog(null,"Combo modificado correctamente."+ "\nNuevo precio: ₡"+ combo.calcularPrecioTotal());
                    break;
                }
            }

            if (!encontrado){
                JOptionPane.showMessageDialog(null,"No existe un combo con ese ID.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"El ID y el descuento deben ser números válidos.");
        }
    }//GEN-LAST:event_btnModificarComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCombos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCombos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCombos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCombos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCombos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarCombo;
    private javax.swing.JButton btnModificarCombo;
    private javax.swing.JButton btnMostrarCombos;
    private javax.swing.JButton btnRegistrarCombo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtMostrarCombos;
    // End of variables declaration//GEN-END:variables
}
